---
apiVersion: pulsar.streamnative.io/v1alpha1
kind: PulsarBroker
metadata:
  name: broker
  namespace: sn-pulsar
spec:
  image: streamnative/pulsar:2.9.2.15
  pod:
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
    terminationGracePeriodSeconds: 30
  config:
    custom:
      webSocketServiceEnabled: "true"
  replicas: 2
  zkServers: zookeeper-zk:2181
