apiVersion: v1
kind: Service
metadata:
  labels:
    cloud.streamnative.io/app: pulsar
    cloud.streamnative.io/cluster: zookeeper
    cloud.streamnative.io/component: zookeeper
  name: zookeeper
  namespace: pulsar
spec:
  ports:
  - name: tcp-client
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: http-metrics
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: http-admin
    port: 9990
    protocol: TCP
    targetPort: 9990
  selector:
    cloud.streamnative.io/app: pulsar
    cloud.streamnative.io/cluster: zookeeper
    cloud.streamnative.io/component: zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
